$(eval $(call addlib,sourcemeta_jsontoolkit_test))

SOURCEMETA_JSONTOOLKIT_TEST_CXXFLAGS-y += --std=c++20
TEST_BASE := $(SOURCEMETA_JSONTOOLKIT_TEST_BASE)/../test

# JSON
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/json/json_array_test.cc
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/json/json_boolean_test.cc
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/json/json_error_test.cc
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/json/json_integer_test.cc
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/json/json_null_test.cc
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/json/json_number_test.cc
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/json/json_object_test.cc
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/json/json_parse_error_test.cc
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/json/json_parse_test.cc
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/json/json_prettify_test.cc
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/json/json_real_test.cc
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/json/json_string_test.cc
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/json/json_stringify_test.cc
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/json/json_value_test.cc

# JSON Pointer
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/jsonpointer/jsonpointer_error_test.cc
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/jsonpointer/jsonpointer_get_test.cc
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/jsonpointer/jsonpointer_parse_error_test.cc
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/jsonpointer/jsonpointer_parse_test.cc
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/jsonpointer/jsonpointer_pointer_test.cc
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/jsonpointer/jsonpointer_set_test.cc
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/jsonpointer/jsonpointer_stringify_test.cc
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/jsonpointer/jsonpointer_token_test.cc

# URI
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/uri/uri_escape_test.cc
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/uri/uri_fragment_test.cc
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/uri/uri_host_test.cc
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/uri/uri_is_absolute_test.cc
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/uri/uri_recompose_test.cc
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/uri/uri_resolve_from_test.cc
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/uri/uri_test.cc
SOURCEMETA_JSONTOOLKIT_TEST_SRCS-y += $(TEST_BASE)/uri/uri_unescape_test.cc

# TODO: Port the JSON Test Suite
# TODO: Run tests for JSON Schema
