if(NOT Noa_FOUND)
  if(SOURCEMETA_CORE_INSTALL)
    set(NOA_INSTALL ON CACHE BOOL "enable Noa installation")
  else()
    set(NOA_INSTALL OFF CACHE BOOL "disable Noa installation")
  endif()

  set(NOA_GOOGLETEST ${SOURCEMETA_CORE_TESTS} CACHE BOOL "GoogleTest")
  set(NOA_GOOGLEBENCHMARK ${SOURCEMETA_CORE_BENCHMARK} CACHE BOOL "GoogleBenchmark")
  add_subdirectory("${PROJECT_SOURCE_DIR}/vendor/noa")
  include("${PROJECT_SOURCE_DIR}/vendor/noa/cmake/noa.cmake")
  set(Noa_FOUND ON)
endif()
